'use client'
import { createContext,useCallback,useContext,useEffect,useMemo,useState } from 'react'
import { normalizeQualityValue } from '@/lib/quality-preferences'
type Playlist={id:string;name:string;itemIds:string[];createdAt:number}
type HistoryEntry={id:string;playedAt:number;progress:number}
export type Preferences={defaultVideoQuality:string;defaultAudioQuality:string;rememberQuality:boolean;rememberedVideoQuality:string|null;autoRetry:boolean;networkPreference:'any'|'wifi'}
type Value={favorites:string[];playlists:Playlist[];history:HistoryEntry[];preferences:Preferences;toggleFavorite:(id:string)=>void;createPlaylist:(name:string)=>string;addToPlaylist:(playlistId:string,itemId:string)=>void;removeFromPlaylist:(playlistId:string,itemId:string)=>void;reorderPlaylist:(playlistId:string,from:number,to:number)=>void;recordPlay:(id:string,progress?:number)=>void;clearHistory:()=>void;removeStaleIds:(validIds:string[])=>void;setPreferences:(value:Preferences)=>void;rememberVideoQuality:(value:string)=>void}
const defaults:Preferences={defaultVideoQuality:'ask',defaultAudioQuality:'audio',rememberQuality:true,rememberedVideoQuality:null,autoRetry:true,networkPreference:'any'}
const Context=createContext<Value|null>(null)
export function LibraryProvider({children}:{children:React.ReactNode}){const [favorites,setFavorites]=useState<string[]>([]);const [playlists,setPlaylists]=useState<Playlist[]>([]);const [history,setHistory]=useState<HistoryEntry[]>([]);const [preferences,setPreferences]=useState(defaults);const [ready,setReady]=useState(false)
 useEffect(()=>{try{const raw=localStorage.getItem('reelhouse.library');if(raw){const data=JSON.parse(raw);setFavorites(data.favorites||[]);setPlaylists(data.playlists||[]);setHistory(data.history||[]);setPreferences({...defaults,...data.preferences})}}catch{}finally{setReady(true)}},[])
 useEffect(()=>{if(ready)try{localStorage.setItem('reelhouse.library',JSON.stringify({favorites,playlists,history,preferences}))}catch{}},[ready,favorites,playlists,history,preferences])
 const rememberVideoQuality=useCallback((value:string)=>{const quality=normalizeQualityValue(value);if(quality==='audio')return;setPreferences(current=>current.rememberQuality?{...current,rememberedVideoQuality:quality}:current)},[])
 const toggleFavorite=useCallback((id:string)=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[id,...v]),[]);const createPlaylist=useCallback((name:string)=>{const id=`pl_${Date.now()}`;setPlaylists(v=>[{id,name:name.trim()||'Untitled playlist',itemIds:[],createdAt:Date.now()},...v]);return id},[]);const addToPlaylist=useCallback((playlistId:string,itemId:string)=>setPlaylists(v=>v.map(p=>p.id===playlistId&&!p.itemIds.includes(itemId)?{...p,itemIds:[...p.itemIds,itemId]}:p)),[]);const removeFromPlaylist=useCallback((playlistId:string,itemId:string)=>setPlaylists(v=>v.map(p=>p.id===playlistId?{...p,itemIds:p.itemIds.filter(x=>x!==itemId)}:p)),[]);const reorderPlaylist=useCallback((playlistId:string,from:number,to:number)=>setPlaylists(v=>v.map(p=>{if(p.id!==playlistId)return p;const ids=[...p.itemIds];const [moved]=ids.splice(from,1);ids.splice(to,0,moved);return {...p,itemIds:ids}})),[]);const recordPlay=useCallback((id:string,progress=0)=>setHistory(v=>[{id,playedAt:Date.now(),progress},...v.filter(x=>x.id!==id)].slice(0,100)),[]);const clearHistory=useCallback(()=>setHistory([]),[]);const removeStaleIds=useCallback((ids:string[])=>{const valid=new Set(ids);setFavorites(v=>v.filter(id=>valid.has(id)));setHistory(v=>v.filter(x=>valid.has(x.id)));setPlaylists(v=>v.map(p=>({...p,itemIds:p.itemIds.filter(id=>valid.has(id))})))},[])
 const value=useMemo(()=>({favorites,playlists,history,preferences,toggleFavorite,createPlaylist,addToPlaylist,removeFromPlaylist,reorderPlaylist,recordPlay,clearHistory,removeStaleIds,setPreferences,rememberVideoQuality}),[favorites,playlists,history,preferences,toggleFavorite,createPlaylist,addToPlaylist,removeFromPlaylist,reorderPlaylist,recordPlay,clearHistory,removeStaleIds,rememberVideoQuality]);return <Context.Provider value={value}>{ready?children:null}</Context.Provider>}
export function useLibrary(){const value=useContext(Context);if(!value)throw new Error('useLibrary must be used within LibraryProvider');return value}
